---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: che-gateway
  labels:
    app: che-gateway
  annotations:
    blabol: "1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: che-gateway
  template:
    metadata:
      labels:
        app: che-gateway
    spec:
      shareProcessNamespace: true
      securityContext:
        capabilities:
          add:
          - SYS_PTRACE
      containers:
      - name: haproxy
        image: haproxy:2.1
        command: ["haproxy"]
        args: ["-W", "-f", "/usr/local/etc/haproxy"]
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: config
          mountPath: /usr/local/etc/haproxy/
      - name: controller
        image: bash
        command: ["sleep"]
        args: ["infinity"]
      volumes:
      - name: config
        configMap:
          name: haproxy-config
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: haproxy-config
data:
  haproxy.cfg: |
    global
      debug

    defaults
      timeout connect 10s
      timeout client 30s
      timeout server 30s
      mode http

    frontend che
      bind :8080

      default_backend che-server

    backend che-server
      cookie SERVERUSED insert indirect nocache
      server server che:80

---
kind: Service
apiVersion: v1
metadata:
  name: che-gateway
spec:
  selector:
    app: che-gateway
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---
kind: Pod
apiVersion: v1
metadata:
  name: che
  labels:
    app: che
spec:
  containers:
  - name: server
    image: quay.io/lkrejci/echo-server:latest
    env:
    - name: ECHO_NAME
      value: "Che"
    - name: ECHO_PORT
      value: "3000"
---
kind: Service
apiVersion: v1
metadata:
  name: che
spec:
  selector:
    app: che
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
