---
kind: ConfigMap
apiVersion: v1
metadata:
  name: gateway-che-router
  labels:
    che-config-role: gateway
data:
  che.yml: |
    http:
      routers:
        che:
          rule: "PathPrefix(`/`)"
          service: che-service
          priority: 1
      services:
        che-service:
          loadBalancer:
            servers:
            - url: 'http://che'          
