# This file defines the main infrastructure components of the "che server".
# It contains the "gateway" implemented using Traefik and the "che server"
# implemented as a simple nginx server serving one static file.
---

# This is the Gateway implemented using Traefik. This is where the inbound
# traffic gets handled.
kind: Pod
apiVersion: v1
metadata:
  name: che-gateway
  labels:
    app: che-gateway 
spec:
  serviceAccountName: gateway-config
  containers:
  - name: traefik
    image: quay.io/lkrejci/traefik-openshift:2.2.0
    volumeMounts:
    - name: config
      mountPath: /etc/traefik
    - name: exposures
      mountPath: "/che-exposures"
  - name: config-map-sync
    image: quay.io/lkrejci/cm-bump:latest
    env:
    - name: CM_TLS_VERIFY
      value: "false"
    - name: CM_DIR
      value: "/che-exposures"
    - name: CM_LABELS
      value: "che-config-role==gateway"
    - name: CM_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    - name: CM_LOG
      value: info,cm_bump=debug
    volumeMounts:
    - name: exposures
      mountPath: "/che-exposures"
  volumes:
  - name: config
    configMap:
      name: traefik-config
  - name: exposures
    emptyDir: {}
---

# This is the main configuration for Traefik. We configure it to listen
# for changes in the "/che-exposures" directory - where we put all the
# configuration from the "che-exposures" config map.
kind: ConfigMap
apiVersion: v1
metadata:
  name: traefik-config
data:
  traefik.yml: |
    global:
      checkNewVersion: false
      sendAnonymousUsage: false
    entrypoints:
      http:
        address: ":8080"
      https:
        address: ":8443"   
    providers:
      file:
        directory: "/che-exposures"
        watch: true
    log:
      level: DEBUG
