---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: che-gateway
  labels:
    app: che-gateway
  annotations:
    blabol: "1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: che-gateway
  template:
    metadata:
      labels:
        app: che-gateway
    spec:
      containers:
      - name: haproxy
        image: haproxy:2.1
        command: ["haproxy"]
        args: ["-W", "-f", "/usr/local/etc/haproxy"]
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: config
          mountPath: /usr/local/etc/haproxy/
      volumes:
      - name: config
        configMap:
          name: haproxy-config
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: haproxy-config
data:
  haproxy.cfg: |
    global

    defaults
      timeout connect 10s
      timeout client 30s
      timeout server 30s
      mode http

    frontend che
      bind :8080

      use_backend %[path,map_beg(/usr/local/etc/haproxy/cherouter.map)]

      default_backend che-server

    backend che-server
      cookie SERVERUSED insert indirect nocache
      server server che:80
  cherouter.map: |
