# The main route. Update the host to work in your environment.
kind: Route
apiVersion: v1
metadata:
  namespace: gtw-che
  name: che-gateway 
spec:
  host: test-che-gateway.192.168.42.225.nip.io 
  path: /
  to:
    kind: Service
    name: che-gateway

