---
kind: ConfigMap
apiVersion: v1
metadata:
  namespace: gtw-che
  name: gateway-config-ws-1 
  labels:
    che-config-role: gateway
data:
  ws-1.yml: |
    http:
      routers:
        ws-1:
          rule: "PathPrefix(`/ws-1`)"
          service: ws-1
          middlewares: ["ws-1"]
          priority: 2
      services:
        ws-1:
          loadBalancer:
            servers:
            - url: 'http://ws-1.gtw-usr1'
      middlewares:
        ws-1:
          stripPrefix:
            prefixes:
            - "/ws-1"
---
kind: Pod
apiVersion: v1
metadata:
  namespace: gtw-usr1
  name: ws-1
  labels:
    app: ws-1
spec:
  containers:
  - name: server
    image: quay.io/lkrejci/echo-server:latest 
    env:
    - name: ECHO_NAME
      value: "ws-1"
    - name: ECHO_PORT
      value: "3000"
---    
kind: Service
apiVersion: v1
metadata:
  namespace: gtw-usr1
  name: ws-1
spec:
  selector:
    app: ws-1
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
