---
kind: ConfigMap
apiVersion: v1
metadata:
  namespace: gtw-che
  name: gateway-config-main 
  labels:
    che-config-role: gateway
data:
  che.location: |
    location / {
        proxy_pass http://che;
    }
