---
kind: ConfigMap
apiVersion: v1
metadata:
  name: gateway-che-location
  labels:
    che-config-role: gateway
data:
  che.location: |
    location / {
        proxy_pass http://che;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
    }
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: gateway-server-config
data:
  nginx.conf: |

    worker_processes  1;

    error_log  /var/log/nginx/error.log warn;
    pid        /tmp/nginx.pid;


    events {
        worker_connections  1024;
    }


    http {
        proxy_temp_path /tmp/proxy_temp;
        client_body_temp_path /tmp/client_temp;
        fastcgi_temp_path /tmp/fastcgi_temp;
        uwsgi_temp_path /tmp/uwsgi_temp;
        scgi_temp_path /tmp/scgi_temp;

        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;

        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';

        access_log  /var/log/nginx/access.log  main;

        sendfile        on;
        #tcp_nopush     on;

        keepalive_timeout  65;

        #gzip  on;

        # This is needed for correct websocket handling
        map $http_upgrade $connection_upgrade {
          default upgrade;
          ''      close;
        }

        include /etc/nginx/conf.d/*.conf;
    }

