kind: Pod
apiVersion: v1
metadata:
  name: che-gateway
  labels:
    app: che-gateway 
spec:
  serviceAccountName: gateway-config
  containers:
  - name: gateway 
    image: quay.io/lkrejci/cm-bump-nginx-prototype 
    imagePullPolicy: Always
    env:
    - name: CM_TLS_VERIFY
      value: "false"
    - name: CM_LABELS
      value: "che-config-role==gateway"
    - name: CM_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    - name: CM_PROC_CMD
      value: "nginx: master.*"
    - name: CM_PROC_SIGNAL
      value: SIGHUP
    - name: CM_LOG
      value: info,cm_bump=trace
    - name: DNS_TTL
      value: 5s
