---
kind: ConfigMap
apiVersion: v1
metadata:
  namespace: gtw-che
  name: gateway-config-ws-1 
  labels:
    che-config-role: gateway
data:
  ws-1.location: |
    location /ws-1 {
      proxy_pass http://ws-1.gtw-usr1;
    }
---
kind: Pod
apiVersion: v1
metadata:
  namespace: gtw-usr1
  name: ws-1
  labels:
    app: ws-1
spec:
  containers:
  - name: server
    image: quay.io/lkrejci/echo-server:latest 
    env:
    - name: ECHO_NAME
      value: "ws-1"
    - name: ECHO_PORT
      value: "3000"
---    
kind: Service
apiVersion: v1
metadata:
  namespace: gtw-usr1
  name: ws-1
spec:
  selector:
    app: ws-1
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
