---
kind: ConfigMap
apiVersion: v1
metadata:
  namespace: gtw-che
  name: gateway-config-ws-2 
  labels:
    che-config-role: gateway
data:
  ws-2.location: |
    location /ws-2 {
      proxy_pass http://ws-2.gtw-usr2;
    }
---
kind: Pod
apiVersion: v1
metadata:
  namespace: gtw-usr2
  name: ws-2
  labels:
    app: ws-2
spec:
  containers:
  - name: server
    image: quay.io/lkrejci/echo-server:latest
    env:
    - name: ECHO_NAME
      value: "ws-2"
    - name: ECHO_PORT
      value: "3000"
---    
kind: Service
apiVersion: v1
metadata:
  namespace: gtw-usr2
  name: ws-2
spec:
  selector:
    app: ws-2
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
