kind: ConfigMap
apiVersion: v1
metadata:
  name: haproxy-config-main
data:
  haproxy.cfg: |
    global

    defaults
      timeout connect 10s
      timeout client 30s
      timeout server 30s
      mode http

    frontend che
      bind :8080

      use_backend %[path,map_beg(/tmp/haproxy-config/cherouter.map)]

      default_backend che-server

    backend che-server
      cookie SERVERUSED insert indirect nocache
      server server che:80
