---
kind: ConfigMap
apiVersion: v1
metadata:
  namespace: gtw-che
  name: che-exposures
  labels:
    che-config-role: gateway
data:
  che.yml: |
    http:
      routers:
        che:
          rule: "PathPrefix(`/`)"
          service: che-service
          priority: 1
      services:
        che-service:
          loadBalancer:
            servers:
            - url: 'http://che'          
  ws-1.yml: |
    http:
      routers:
        ws-1:
          rule: "PathPrefix(`/ws-1`)"
          service: ws-1
          middlewares: ["ws-1"]
          priority: 2
      services:
        ws-1:
          loadBalancer:
            servers:
            - url: 'http://ws-1.gtw-usr1'
      middlewares:
        ws-1:
          stripPrefix:
            prefixes:
            - "/ws-1"
  ws-2.yml: |
    http:
      routers:
        ws-2:
          rule: "PathPrefix(`/ws-2`)"
          service: ws-2
          middlewares: ["ws-2"]
          priority: 2
      services:
        ws-2:
          loadBalancer:
            servers:
            - url: 'http://ws-2.gtw-usr2'
      middlewares:
        ws-2:
          stripPrefix:
            prefixes:
            - "/ws-2"
---
kind: Pod
apiVersion: v1
metadata:
  namespace: gtw-usr1
  name: ws-1
  labels:
    app: ws-1
spec:
  containers:
  - name: server
    image: quay.io/lkrejci/echo-server:latest 
    env:
    - name: ECHO_NAME
      value: "ws-1"
    - name: ECHO_PORT
      value: "3000"
---    
kind: Service
apiVersion: v1
metadata:
  namespace: gtw-usr1
  name: ws-1
spec:
  selector:
    app: ws-1
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
---
kind: Pod
apiVersion: v1
metadata:
  namespace: gtw-usr2
  name: ws-2
  labels:
    app: ws-2
spec:
  containers:
  - name: server
    image: quay.io/lkrejci/echo-server:latest
    env:
    - name: ECHO_NAME
      value: "ws-2"
    - name: ECHO_PORT
      value: "3000"
---    
kind: Service
apiVersion: v1
metadata:
  namespace: gtw-usr2
  name: ws-2
spec:
  selector:
    app: ws-2
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
