apiVersion: v1
kind: ServiceAccount
metadata:
  name: traefik-ingressroute-controller
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: traefik-ingressroute-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: traefik-ingressroute-controller
subjects:
  - kind: ServiceAccount
    name: traefik-ingressroute-controller
    namespace: {{POC_NAMESPACE}}
---    
kind: Deployment
apiVersion: apps/v1
metadata:
  name: che-gateway
  labels:
    app: che
spec:
  replicas: 1
  selector:
    matchLabels:
      app: che-gateway
  template:
    metadata:
      labels:
        app: che-gateway
    spec:
      serviceAccountName: traefik-ingressroute-controller
      containers:
        - name: traefik
          image: traefik:v2.2
          args:
            - --api.insecure
            - --accesslog
            - --entrypoints.web.Address=:8000
            - --entrypoints.websecure.Address=:4443
            - --providers.kubernetescrd
          ports:
            - name: web
              containerPort: 8000
            - name: websecure
              containerPort: 4443
            - name: admin
              containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: che-gateway
spec:
  ports:
    - protocol: TCP
      name: web
      port: 8000
    - protocol: TCP
      name: admin
      port: 8080
    - protocol: TCP
      name: websecure
      port: 4443
  selector:
    app: che-gateway
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: che
spec:
  entryPoints:
    - web
  routes:
  - match: PathPrefix(`/`)
    priority: 1
    kind: Rule
    services:
    - name: che
      namespace: {{POC_NAMESPACE}}
      port: 80
